osx_image: xcode11
dist: trusty
sudo: false
language: node_js
node_js:
  - node
os:
  - osx
env:
  global:
    - ELECTRON_CACHE=$HOME/Library/Caches/electron
    - ELECTRON_BUILDER_CACHE=$HOME/Library/Caches/electron-builder
    - secure: mUXd3/jUnH2AZPjjvHBxIgaeJfen2rMKS/YaGg+TAVAHWeZDvlWNdOi9SFsLIIeEnY6ekL69K7UyMN6lMe5cvRsWoJU4qrpHKa852AYOrUKB/mB09Y7T76O/5tc6EY1lIxmaAbviVSFQPNpMkvAWHEdrU11NIKGaZWiFiyHjRhQJwCQMDNI/YPLRCuWKftsAHVSKF3juqsVt0tYpRIXIcXXAavbr2fkYoPVCo19LvgPXcVKAgvsdIgL1z3qf+F9T+eooSwiZtjYpJi8tT6AyWve2AtsDVlbGKLEDJamGEEnqTs6qdep3imNKjNm1QlYLx/pqydrh3z+KCh/MHi+46WtpuFSadV0VYmUuWoMU1WtdFl6NrQgOe200BHfSUwisMqTCZiDr937Ra2zbSk8S7FJyaCpYC8eAt7MRhHDPnsrsb110SoDtp7ryoEkfwr8IUVCBlki77JgUA96Al/Y6P09fpeNWSj3PZuPQS+Yn5qi2dwYr6QdhNZP4meAL0Ky2xS9gLrPB/IKJ/5St6Zh9WsA3u4YvVWZ9BVIFuknJYMjzMqmqijIjblOTShHSDOuaLPLV5zIuRejbqaRjuy0moT9ToMSQpPD/X3bV71klzf+tfViivUidnCEV83+e+ztqbCI1xl7kEVI1w7yzYPT2HcEUe383nDciL8nOfyzarbg=
    - secure: t7xashmJUmUJYIA/3IqHP9YnupK0or9XPSswLehctDW4sjSmzP0pWDFK0IhPcb1NK0RhNXmsb/K2eurPqfaW6b6BvyRx8XYVto0h3x4tigTEjlA4IJLdchTBH17R1cT/tVAcG7g3fyCEk2IcQCG/uVrKhEYaNukAMtiBWhyXbQpAKRqLyZTEwZCNDTBP4sLNCbNf/PoDBfcuIraz5UYq0L14UFVOXsxnUefwWimUIV35TWGGnFvGhtKQLOfXv0h1POew9QQU214ixYs2jZdZTGMsxH+y3He+Xtl5r161RKb46TmwOK4GFWt/msAX2Xv91NLMXp6CAUps/P8xu58YbZasgXyYkgw/ka0hbs3utcT2YxKVYOYtfbZIBMntH0rMOR0c9m9J7I9QHGcl/U+WhBBVVenKUZ8sRtbI0k+Jqkbmf9HTdvzyJuIteiz/TsShSQrslbDOdbDr+FaWHhyR9x3fUY13R8m5AZeANJO6Qe2u3eHLPzKplXe4KpYMd/dX5Ccdai9jMHuW3rIs6VKL/+Idt4Wpp7QY0cAx1xoaj2lU/whtKDa7I7aYqAqZtztQToJox1eRTBg8g+jctRqtU9A8X4P+nwCYjplrbihk6bIweDhc/+BE+/EL2YXKep5w/fRWqxwlRIcjRas9JKvqOKVmqxDBaiOdCUUJhPU4mnU=
script:
  - yarn run check
  - "./ci-build.sh"
after_success:
  - yarn run coveralls
